### ISSUE TITLE
depending on library

### ISSUE THREAD

**Issue by ammark47** [georgeOsdDev/react-web-notification#11]
Is there anyway for me to import from 'react-web-notification' as opposed to '../src/components/Notification' ? I believe its more dependable and safer.

**Comment by georgeOsdDev** [comment]
@ammark47 
I fixed `main` in `package.json` (5ba84a3) and released v0.2.1 to NPM.
Thanks!

**Comment by ammark47** [comment]
Sorry, I don't think I explained myself properly. I believe its safer to be able to to this: import Notification from 'react-web-notification'  rather than import Notification from '**../src/components/**Notification'

**Comment by georgeOsdDev** [comment]
You can use it in your app like below
```
import Notification  from 'react-web-notification';
```
Because `example` folder does not have package.json, so it use `src` directory.
