### ISSUE TITLE
Playing a sound

### ISSUE THREAD

**Issue by jonathanasquier** [georgeOsdDev/react-web-notification#13]
Hey, I'm using a mp3 link in options.sound to play when the notification opens, but I can't get it to work.
Does it work on your side?
Am I missing something?

Thanks!

**Comment by georgeOsdDev** [comment]
Hi @jonathanasquier 
MDN say that `Notification.sound` is not supported in any browser yet.
https://developer.mozilla.org/en/docs/Web/API/notification/sound#Browser_compatibility

I think you can emulate notification sound like this solution
http://stackoverflow.com/questions/10105063/how-to-play-a-notification-sound-on-websites

```
playSound(){
  // See
  // http://stackoverflow.com/questions/10105063/how-to-play-a-notification-sound-on-websites
}

<Notification
    onShow={this.playSound.bind(this)}
...
```

**Comment by georgeOsdDev** [comment]
@jonathanasquier 
I updated example.
https://github.com/georgeOsdDev/react-web-notification/blob/develop/example/app.js#L51

Try demo.
http://georgeosddev.github.io/react-web-notification/example/

Thanks!

**Comment by jonathanasquier** [comment]
Awesome! thanks!

**Comment by vishnusivabalan** [comment]
Hi, is their any document-tutorial for this react-web-notification. i'm new to this.

Thanks.

**Comment by georgeOsdDev** [comment]
Please check below files.
https://github.com/georgeOsdDev/react-web-notification/blob/master/README.md
https://github.com/georgeOsdDev/react-web-notification/blob/master/example/app.js

**Comment by vishnusivabalan** [comment]
Thanks for your response, i need some document or tutorial for my better understanding of your code flow and structure.

**Comment by georgeOsdDev** [comment]
This component is just 180 lines.

https://github.com/georgeOsdDev/react-web-notification/blob/master/src/components/Notification.js

I have no plans to write a tutorial.

**Comment by vishnusivabalan** [comment]
Okay Thanks.
