### ISSUE TITLE
Permission being repeatedly asked for in Safari

### ISSUE THREAD

**Issue by eliseumds** [georgeOsdDev/react-web-notification#15]
If the *Notification* component is re-rendered and the user didn't grant permission yet, it's gonna stack up and ask again.

**Comment by georgeOsdDev** [comment]
Hi @eliseumds 

I added `askAgain` prop(default `false`).
If `true` it will call `window.Notification.requestPermission` again even if it was denied before.

btw,
I think it would be nice that you use this component on your root Application,
If so, this lib ask permission on `componentDidMount `, and `componentDidMount` will be called only once.

Thanks
