### ISSUE TITLE
Multiple identical notifs, for multiple opened tabs

### ISSUE THREAD

**Issue by jonathanasquier** [georgeOsdDev/react-web-notification#18]
Hi,
my app receives socket.io notifications which I display as web notifications.
If multiple instances of my app are opened in multiple browser tabs, I get as many identical notifs as the number of opened tabs (which seems quite logical). I'm using the "tag" option in the options object to prevent this behaviour, but nothing seems to change.

Am I missing something regarding tags?

Thanks a lot

**Comment by georgeOsdDev** [comment]
Currently this component offer just `disableActiveWindow ` prop. 
https://github.com/georgeOsdDev/react-web-notification/blob/master/src/components/Notification.js#L108
If `disableActiveWindow = true`, notification will be ignored when current tab is active(has focus).
If there are many non-active tabs with this component as same code in your browser, there will be Notification on each non-active tabs.

I have no idea to control communication between tabs with this component,
But I think you can control in you App side's `render` or `shoudComponentUpdate` method.
It is possible to communicate between tabs if tabs working with same domain by using `localStorage` and `storage` event. (https://developer.mozilla.org/en-US/docs/Web/Events/storage)

If you have any good idea, please make PR.
Thanks!!

**Comment by jonathanasquier** [comment]
I just made a few tests on the repo and tags work pretty well in the same browser tab.
As you said the behaviour I'm trying to implement is out of the scope of this repo.
I'm going to give localStorage a try!

Thanks

**Comment by jonathanasquier** [comment]
Eventually I went for a `SharedWorker` that simply messages every tab on open/close which one is "main" and `setIgnore(true)` every other. This way only one opened tab has the right to display notifications, and the right is transfered on close.
Works pretty well :)

**Comment by georgeOsdDev** [comment]
Nice :+1:
