### ISSUE TITLE
Compile before publishing

### ISSUE THREAD

**Issue by Purii** [georgeOsdDev/react-web-notification#2]
Great component! :-)

But I have a problem using it in a webpack project. When I configure webpack to `exclude: /node_modules/` the component doesn't get compiled. The result is at least an error with the JSX in the render function.

I saw at other projects, that the components are published in a compiled format, like a recent one from gaearon: https://github.com/gaearon/react-proxy

Do you have other suggestions?

**Comment by georgeOsdDev** [comment]
Hi @Purii,

I added webpack build task and released v0.1.1(contains dist/ReactWebNotification.js) to the NPM.
I'm not familiar with webpack, so if it not works, please create PR :)
