### ISSUE TITLE
not working on android chrome

### ISSUE THREAD

**Issue by jurgob** [georgeOsdDev/react-web-notification#22]
My phone is a nexus 6p with android 7.0 version installed

**Comment by georgeOsdDev** [comment]
http://caniuse.com/#feat=notifications

I think we need `webkit` prefix.
https://github.com/georgeOsdDev/react-web-notification/blob/master/src/components/Notification.js#L22

I'm welcome your PR.

**Comment by jamesfry** [comment]
This seems a little more complicated - the browser prompts to request notifications fine, so the problem appears to be on line 115 where the new Notification is created (have yet to remote debug) - Chrome on Android doesn't support that apparently, instead preferring one creates an empty service worker instead (see the accepted answer on this SO question, and the comment from Miguel Garcia - http://stackoverflow.com/questions/31512504/html5-notification-not-working-in-mobile-chrome.

**Comment by georgeOsdDev** [comment]
I think we need serviceWorker for Android chrome and application server needs host "sw.js".
I think that it exceeds the range of functions that this library can provide with an import statement.

**Comment by coluccini** [comment]
Hi!
If we host/register the sw.js the component would work on Android/Chrome

**Comment by oztek22** [comment]
any update or workaround for this bug?

**Comment by joekr** [comment]
To work on mobile you need to use serviceWorker like @georgeOsdDev said.

It seems like a quick fix might be to update https://github.com/georgeOsdDev/react-web-notification/blob/master/src/components/Notification.js#L21 to something like

```javascript
if (('Notification' in window) && window.Notification) {
    try {
      new window.Notification('');
      supported = true;
    } catch (e) {
      if (e.name === 'TypeError') {
        supported = false;
      }
    }
  if (window.Notification.permission === PERMISSION_GRANTED) {
    granted = true;
  }
}
```

A few other projects mention this as well https://github.com/alexgibson/notify.js/issues/38 with a fix of https://github.com/alexgibson/notify.js/blob/master/src/notify.js#L74

My quick fix is to update `handlePermissionGranted` from this

```javascript
handlePermissionGranted() {
  this.setState({ ignore: false });
}
```

To something like this:
```javascript
handlePermissionGranted() {
  let ignore = false;
  try {
    new window.Notification('');
  } catch (e) {
    if (e.name === 'TypeError') {
      ignore = true;
    }
  }
  this.setState({ ignore });
}
```

**Comment by georgeOsdDev** [comment]
See
#41

**Comment by pankti1210** [comment]
i am trying to implement Service Worker.. but i got this error **this.props.swRegistration.showNotification is not a function**

![error](https://user-images.githubusercontent.com/18523264/61877805-64145300-af0d-11e9-8cfa-c16ffcb54fdc.png)


please guide me what to pass in **swRegistration: object,**

**Comment by georgeOsdDev** [comment]
@pankti1210 
↓↓↓
https://mobilusoss.github.io/react-web-notification/example/serviceWorker.html
https://github.com/mobilusoss/react-web-notification/blob/master/example/app.js#L123-L128

**Comment by pankti1210** [comment]
getting blank array in 
`this.props.swRegistration.getNotifications({}).then((notifications) => {
      console.log(notifications);
 });`

and error **Uncaught (in promise) undefined**

**Comment by pankti1210** [comment]
notifications are working in firefox but not in chrome
in chrome i get this error **Uncaught (in promise) undefined** and notifications list blank

**Comment by moradewicz** [comment]
Are you testing this on HTTPS ?

**Comment by pankti1210** [comment]
yes..i have tested on HTTPS too.. 
notifications are only working in web ( Firefox ) 
also not working in mobile browsers.

**Comment by pankti1210** [comment]
@georgeOsdDev  it is working now.. thanks 
but notification sound is not working..

**Comment by georgeOsdDev** [comment]
See https://github.com/mobilusoss/react-web-notification#known-issues
> Notification.sound Notification.sound is not supported in any browser.

We can play sound with [`onShow`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/onshow) callback with standard `Notification` API.
But with `swRegistration` we  can not recognize `show` event.

> swRegistration : ServiceWorkerRegistration. Use this prop to delegate the notification creation to a service worker. See also (https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) ⚠️ onShow, onClick, onClose and onError handlers won't work when notification is created by the service worker.

https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent

BTW
Please do not start discussion using closed issue.
If you found some bug or need any help, please open new issue.
