### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by agnellvj** [georgeOsdDev/react-web-notification#24]
I am having an issue with creating a Web Notification when I create my own component that uses your lib. It works when I load the app first and then I navigate to another page and I reference your Notification lib from my component. It doesn't work when I load it on the first page that gets loaded.

Not sure how to work around this. I am just wondering if there is a way to check for `window` and if the feature is available somewhere else besides the constructor.

**Comment by georgeOsdDev** [comment]
I think you have something build issue because `window` object is global on browser runtime.
I'm not sure #25 is the best solution for your issue.

**Comment by agnellvj** [comment]
The problem can be recreated  if you create a component that renders your Notification component and you insert it as the first page you ever navigate too. The example skirts around the issue by manually calling render after window has been created and the Dom is loaded.

**Comment by georgeOsdDev** [comment]
I can't reproduce `window` as undefined.

```
<script>console.log(0, typeof window)</script>
<!DOCTYPE html>
<script>console.log(1, typeof window)</script>
<html>
  <script>console.log(2, typeof window)</script>
  <head>
    <script>console.log(3, typeof window)</script>
    <meta charset="utf-8">
    <title>title</title>
    <script>console.log(4, typeof window)</script>
  </head>
  <body>
    <script>console.log(5, typeof window)</script>
  </body>
  <script>console.log(6, typeof window)</script>
</html>
<script>console.log(7 , typeof window)</script>
```
console say
test.html:1 0 "object"
test.html:3 1 "object"
test.html:5 2 "object"
test.html:7 3 "object"
test.html:10 4 "object"
test.html:13 5 "object"
test.html:15 6 "object"
test.html:17 7 "object"
