### ISSUE TITLE
Not focusing tab in Chrome

### ISSUE THREAD

**Issue by plainspace** [georgeOsdDev/react-web-notification#26]
Clicking the Desktop notification, doesn't focus the tab in Chrome - Version 54.0.2840.98 (64-bit)

**Comment by vasuchawla** [comment]
same issue! tried using `window.focus()` but no luck :(

**Comment by georgeOsdDev** [comment]
This is browser issue not this component's issue.

Please try 
```
parent.focus();
```
http://stackoverflow.com/questions/4906976/how-to-get-focus-to-a-chrome-tab-which-created-desktop-notification
