### ISSUE TITLE
Update gh-pages to use latest version

### ISSUE THREAD

**Issue by jfsiii** [georgeOsdDev/react-web-notification#32]
The demo at https://georgeosddev.github.io/react-web-notification/example/ does not work in Chrome Stable (ver 62)

The following messages are in the console:

 * `[Violation] Only request notification permission in response to a user gesture.`
 * `Permission Denied`

I believe this is because the `gh-pages` branch is using an old version of the component which fires `requestPermission` in `componentDidMount` instead of in response to a user action. I see this has been changed in `master`.

**Comment by davidsonsns** [comment]
@jfsiii 
It worked normally in my chrome.
Have you modified the hosts file? For security reasons this API (Notification) works in sites https and for development one must use localhost only.

**Comment by jfsiii** [comment]
I don't think this has anything to do with my computer. Thanks for pointing out that the README links to http vs https. I'll open a PR for that.

That doesn't address the `[Violation]`, though. The issue is that the `gh-pages` branch is using an old version of the component which fires `requestPermission` in `componentDidMount` instead of in response to a user action
<img width="978" alt="screen shot 2017-11-14 at 9 34 26 am" src="https://user-images.githubusercontent.com/57655/32794967-2a52c762-c91f-11e7-80f0-893e7f9459de.png">

**Comment by georgeOsdDev** [comment]
Now it working
