### ISSUE TITLE
Why did you choose the latest React as the dependency?

### ISSUE THREAD

**Issue by KevinYaoooooo** [georgeOsdDev/react-web-notification#35]
I mean, lower version could also work, right?

You should not use the latest React, otherwise all projects have to upgrade to the latest React, it's gonna be a huge change for old projects, or even new projects, that will make many potential users give up your library, I suggest you make your lib be compatible  at least from React v15.5.4, cause that's the most stable version so far, besides, the notification API has nothing to do with latest React APIs, plus the latest React is not stable enough.

**Comment by georgeOsdDev** [comment]
@KevinYaoooooo 
Please try
react-web-notification@0.3.1
Thanks!
